name: Bingxin Lao
description: Personal website
menu:
- page: About
  url: /about
- page: Curriculum Vitae
  url: /cv
  links:
  - title: Education
    url: "#education"
  - title: Research Experience
    url: "#Research_Experience"
- page: Papers
  url: /papers
  links:
  - title: Published papers
    url: "#published-papers"
  - title: Preprints
    url: "#preprints"
- page: Lecture Notes
  url: /lecture_note
  links:
  - title: "Project One"
    url: "#project-one"
  - title: "Project Two"
    url: "#project-two"
  - title: "Project Three"
    url: "#project-three"
  - title: "Project Four"
    url: "#project-four"
menu_external:
- title: Google scholar
  url: "https://scholar.google.com/citations?hl=en&user=7bOjt-AAAAAJ"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: Bingxin-Lao.github.io
locale: en_GB
output: html_document
bibliography: publications.bib  
